apiVersion : apps/v1
kind: Deployment
metadata:
  name: "hari-github-actions"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "hari-github-actions"
  template:
    metadata:
      labels:
        app: "hari-github-actions"
    spec:
      containers:
        - name: "hari-github-actions"
          image: "haricontainerregistry007.azurecr.io/azurevote"
          ports:
          - containerPort: 80