apiVersion: v1
kind: Service
metadata:
    name: "hari-github-actions"
    labels:
        app: "hari-github-actions"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "hari-github-actions"